Revert "fix derp"
hardware/qcom/audio/hal/audio_hw.c:3746:53: error: format specifies type 'long' but the argume
nt has type 'ssize_t' (aka 'int') [-Werror,-Wformat]
                    "%s: error %ld - %s", __func__, ret, pcm_get_error(out->pcm));

This reverts commit b3398b377b1afee26bceaa560f2ca583bc2dd996.

Change-Id: I1c521b6eb73e4e963ab66a61f54e0beee9a08ada